

Card_Layout:
  Hearts: Ace, 2, 3, 4, 5, 6, 7, 8, 9, 10, Jack, Queen, King
  Diamonds: Ace, 2, 3, 4, 5, 6, 7, 8, 9, 10, Jack, Queen, King
  Spades: Ace, 2, 3, 4, 5, 6, 7, 8, 9, 10, Jack, Queen, King
  Clubs: Ace, 2, 3, 4, 5, 6, 7, 8, 9, 10, Jack, Queen, King

Card_Values:
  Ace: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: 10
  Jack: 10
  Queen: 10
  King: 10